### PR TITLE
UK translations files in russian

### PR DESCRIPTION
**Pull request by tomgs**
Not exactly sure how it happened, but russian files found their way into the UK folder.
Deleted that folder, please merge it and I'll upload a new one soon.
Actually, do we need a differnt UK locale at all?

### CODE REVIEW

**Comment by wbaumann** [comment]
I actually think it's okay (although it has confused me before too...). The `UK` is for `Ukrainian` as opposed to `UK-English`, so it should be good as is :). One of the contributors to Smart Receipts is Ukrainian, so that individual helped supply some of the translations from Russian to Ukrainian :)

**Comment by wbaumann** [comment]
You may need to rebase the branch changes against your branch first too. I can walk you through this tomorrow!

**Comment by tomgs** [comment]
Awesome, let's talk. :)

**Comment by tomgs** [comment]
Hey Man,

I know I have a bit more to do, but some things came up!
Will wrap up in the following days, sorry for the delay.

Tom

**Comment by wbaumann** [comment]
Hey no worries or rush at all! Have a good one :)

**Comment by tomgs** [comment]
No need for that now

**Pull request closed without merging**
